import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/navber';
import Footer from './components/footer';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      
      
      
      <body class="flex flex-col min-h-screen">
        <main class="flex-grow">
          <Navbar />
          {children}
        </main>
        <Footer/>
        </body>
        
    </html>
  );
}
